services:
  postgres:
    image: docker.m.daocloud.io/library/postgres:16  # 或改为 postgres:16
    container_name: postgres-root
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: docker.m.daocloud.io/library/redis:6.2  # 或改为 redis:6.2
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: docker.m.daocloud.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"   # API 端口
      - "9001:9001"   # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  zookeeper_data:
  zookeeper_datalog:
  postgres_data:
  redis_data:
  minio_data:
